### ISSUE TITLE
[Bug] Incorrect size value & mutation original declaration value

### ISSUE THREAD

**Issue by retyui** [SuperOl3g/postcss-image-set-polyfill#13]
Demo: https://runkit.com/retyui/5941ce97106bda0012f4676b
Debug stdout:
![image](https://user-images.githubusercontent.com/4661784/27159780-5e614fac-5178-11e7-9ee6-f005a5afa8d6.png)

```css
.test{
     bg: image-set(url('../img/cancel@x3.png') 3x) /* error 👎  */;
     bg: image-set(url('../img/cancel@x3.png') 3x ) /* valid 👍 */;
}
```
Надеюсь предоставленной информации достаточно что бы решить проблему 😄
