### ISSUE TITLE
Nesting in breakpoints?

### ISSUE THREAD

**Issue by strarsis** [SuperOl3g/postcss-image-set-polyfill#21]
Use case:
For a specific set of breakpoints I provide different background images (which can optimize loading time quite nicely). Now I also want to provide three images per pixel density (1x; 2.x and 3x) per breakpoint.
In SASS with webpack [responsive-loader](https://github.com/herrstucki/responsive-loader) this would result in a construct like this:

```css
  // (smallest)
  background-image:
    image-set(
      url(../background.jpg?size=#{$width-smallest}&quality=10) 1dppx,
      url(../background.jpg?size=#{$width-smallest * 2}&quality=10) 2dppx,
      url(../background.jpg?size=#{$width-smallest * 3}&quality=10) 3dppx
    );

@each $width in $widths {
    @media (min-width: #{$width}px) {
      background-image:
        image-set(
          url(../background.jpg?size=#{$width}&quality=10) 1dppx,
          url(../background.jpg?size=#{$width * 2}&quality=10) 2dppx,
          url(../background.jpg?size=#{$width * 3}&quality=10) 3dppx
        );
    }
  }
````

Can this plugin handle these cases?
Can I make the whole thing simpler?
