### ISSUE TITLE
Issues with mixed background values

### ISSUE THREAD

**Issue by strarsis** [SuperOl3g/postcss-image-set-polyfill#4]
@SuperOl3g: 
Using image-set in shorthand with other background values results in just image-set being used:

```scss
.test {
  background: linear-gradient( // solid color workaround
                               // see https://css-tricks.com/tinted-images-multiple-backgrounds/
                  rgba(255, 0, 0, 0.5),
                  rgba(255, 0, 0, 0.5)
                ),
                image-set(  url('../images/bck.jpg')    1x,
                            url('../images/bck@x2.jpg') 2x,
                            url('../images/bck@x3.jpg') 3x  );
}
````

```css
.test {
  background: url(../images/bck.jpg)
}
@media (-webkit-min-device-pixel-ratio:1.5),(min-resolution:144dpi){
  .test{
    background: url(../images/bck@x2.jpg)
  }
}
@media (-webkit-min-device-pixel-ratio:2.25),(min-resolution:216dpi){
  .test {
    background: url(../images/bck@x3.jpg)
  }
}
````
https://astexplorer.net/#/gist/86d1248cc4628f850454d3191c95efec/e0480e393445f6d8d4c696a11438dee0e2632e93

The non-image-set CSS should either be placed outside the mediaqueries as usual or 
with each image-set polyfill for preventing cascading/override issues.
