### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by Semigradsky** [SuperOl3g/postcss-image-set-polyfill#7]
Input:
```css
.image {
  background-image: image-set(
    url(img/test.png) 1x,
    url(img/test-2x.png) 2x,
    url(my-img-print.png) 600dpi
  );
}
```

Expected output:
```css
.image {
  background-image: url(img/test.png);
}
@media (min-resolution: 144dpi) {
  .image {
    background-image: url(img/test-2x.png);
  }
}
@media (min-resolution: 600dpi) {
  .image {
    background-image: url(my-img-print.png);
  }
}
```

Actual output:
```css
.image {
  background-image: url(img/test.png);
}@media (min-resolution: 144dpi) {.image {
  background-image: url(img/test-2x.png);
}
}@media (min-resolution: 600dpi) {.image {
  background-image: url(my-img-print.png);
}
}
```
